package com.hydroline.beacon.gateway;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import java.util.logging.Logger;

/**
 * Mirrors config/hydroline/beacon-provider.json generated by the Provider mod. Located in a separate package to avoid
 * classpath conflicts with mod-side classes.
 */
public final class NettyGatewayConfig {
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final String listenAddress;
    private final int listenPort;
    private final String authToken;
    private final int handshakeTimeoutSeconds;
    private final int idleTimeoutSeconds;

    private NettyGatewayConfig(String listenAddress,
                               int listenPort,
                               String authToken,
                               int handshakeTimeoutSeconds,
                               int idleTimeoutSeconds) {
        this.listenAddress = listenAddress;
        this.listenPort = listenPort;
        this.authToken = authToken;
        this.handshakeTimeoutSeconds = handshakeTimeoutSeconds;
        this.idleTimeoutSeconds = idleTimeoutSeconds;
    }

    public String getListenAddress() {
        return listenAddress;
    }

    public int getListenPort() {
        return listenPort;
    }

    public String getAuthToken() {
        return authToken;
    }

    public int getHandshakeTimeoutSeconds() {
        return handshakeTimeoutSeconds;
    }

    public int getIdleTimeoutSeconds() {
        return idleTimeoutSeconds;
    }

    public boolean isEnabled() {
        return listenPort > 0 && authToken != null && !authToken.isEmpty();
    }

    public static NettyGatewayConfig load(Path configPath, Logger logger) {
        Objects.requireNonNull(configPath, "configPath");
        if (!Files.exists(configPath)) {
            logger.warning("Beacon Provider gateway config not found: " + configPath);
            return null;
        }
        try (InputStream in = Files.newInputStream(configPath)) {
            JsonNode node = MAPPER.readTree(in);
            String listenAddress = node.path("listenAddress").asText("127.0.0.1");
            int listenPort = node.path("listenPort").asInt(0);
            String authToken = node.path("authToken").asText("");
            int handshakeTimeoutSeconds = node.path("handshakeTimeoutSeconds").asInt(10);
            int idleTimeoutSeconds = node.path("idleTimeoutSeconds").asInt(240);
            if (authToken == null || authToken.isEmpty() || "change-me".equalsIgnoreCase(authToken)) {
                logger.warning("Beacon Provider gateway authToken must be configured in " + configPath);
            }
            return new NettyGatewayConfig(listenAddress, listenPort, authToken, handshakeTimeoutSeconds, idleTimeoutSeconds);
        } catch (IOException e) {
            logger.warning("Failed to read Beacon Provider gateway config: " + e.getMessage());
            return null;
        }
    }
}
